table AMZN
	lineageTag: 01880e76-a48d-4bc2-a8ac-5a7616c2edc9

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7c278ee1-c147-436a-8d91-b62c7b566209
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: c56c95fb-c1cd-42ca-82d0-fa5306cf0263
			defaultHierarchy: LocalDateTable_a8dca6f9-ef38-43f5-8961-3030fdd52d12.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Open
		dataType: double
		lineageTag: 4e907a36-45ee-4038-a726-3871e2d3c828
		summarizeBy: sum
		sourceColumn: Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column High
		dataType: double
		lineageTag: 4b8af0db-4beb-415b-93c0-b7825c424b03
		summarizeBy: sum
		sourceColumn: High

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Low
		dataType: double
		lineageTag: 6ac58a84-805e-4612-b325-2ffe84770534
		summarizeBy: sum
		sourceColumn: Low

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Close
		dataType: double
		lineageTag: 02e6697e-7b2e-474c-8dc5-43ba490db31c
		summarizeBy: sum
		sourceColumn: Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Adj Close'
		dataType: double
		lineageTag: f5497196-92f3-45f4-9ffa-c1211e80be02
		summarizeBy: sum
		sourceColumn: Adj Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Volume
		dataType: int64
		formatString: 0
		lineageTag: e4f7cef3-51c2-4052-b5cb-5865520eb5b3
		summarizeBy: sum
		sourceColumn: Volume

		annotation SummarizationSetBy = Automatic

	partition AMZN = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Data Analytics\PBIBroTraining\PBIBroTraining\AMZN.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Open", type number}, {"High", type number}, {"Low", type number}, {"Close", type number}, {"Adj Close", type number}, {"Volume", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

